# Generated by Django 4.0.4 on 2022-06-21 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_orderplaced_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='landmark',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('On the way', 'On the way'), ('Delivered', 'Delivered'), ('Accepted', 'Accepted'), ('Packed', 'Packed'), ('Cancel', 'Cancel')], default='Pending', max_length=50),
        ),
    ]
