# Generated by Django 4.1.3 on 2022-11-01 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_orderplaced_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('On the way', 'On the way'), ('Accepted', 'Accepted'), ('Cancel', 'Cancel'), ('Packed', 'Packed'), ('Delivered', 'Delivered')], default='Pending', max_length=50),
        ),
    ]
