# Generated by Django 4.1.3 on 2022-11-01 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_orderplaced_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Cancel', 'Cancel'), ('Delivered', 'Delivered'), ('On the way', 'On the way'), ('Accepted', 'Accepted'), ('Packed', 'Packed')], default='Pending', max_length=50),
        ),
    ]
