# Generated by Django 4.1.3 on 2022-11-01 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_product_brand_remove_product_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Men', 'Men'), ('Women', 'Women'), ('Child', 'Child')], default=3, max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('On the way', 'On the way'), ('Packed', 'Packed'), ('Cancel', 'Cancel'), ('Accepted', 'Accepted')], default='Pending', max_length=50),
        ),
    ]
